
#damit man die fehler sieht
server:
  error:
    include-message: always
    include-binding-errors: always


#datenbank konfiguration
spring:
  datasource:
    password: aok1
    url: jdbc:mysql://localhost:3306/warehousemanagement
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true